name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: julia --project -e '
            using Pkg; Pkg.instantiate(); Pkg.test()'
    - uses: julia-actions/julia-processcoverage@v1
    - uses: codecov/codecov-action@v1
